#
# Project:    Homework 1
# Programmer: Edwin Flores
# Course:     EN.605.414.81
# Purpose:    Makefile that creates the arg and temp_conv
# 	      libraries
#
ARGDIR=./arg
TEMPCONVDIR=./temp_conv

it:
	$(MAKE) --directory=$(ARGDIR) it
	$(MAKE) --directory=$(TEMPCONVDIR) it

clean:
	$(MAKE) --directory=$(ARGDIR) clean
	$(MAKE) --directory=$(TEMPCONVDIR) clean 
	
install: 
	$(MAKE) --directory=$(ARGDIR) install
	$(MAKE) --directory=$(TEMPCONVDIR) install

depend: 
	$(MAKE) --directory=$(ARGDIR) depend
	$(MAKE) --directory=$(TEMPCONVDIR) depend 
